feature: add Goodbye Page with styling
MaksVibe/feeda pull request #7
Opened 2023-06-28 11:34 UTC by OlesiaTr

- fixed spelling in the theme.js

2023-06-28 11:35 UTC, OlesiaTr commented
This branch was created based on the feature/svgFiles branch

2023-06-28 19:50 UTC, MaksVibe commented
Resolve conflicts pls

2023-06-29 08:03 UTC, MaksVibe commented
Some conflicts, fix it pls, so that I can make merge, thanks

2023-06-29 11:48 UTC, MaksVibe requested changes

2023-06-29 11:48 UTC, MaksVibe commented on components/GoodbyePage/GoodbyePage.tsx
> +    <Reminder>Не забудь перевірити запрошення до Discord</Reminder>
![Screenshot 2023-06-29 at 14 47 01](https://github.com/MaksVibe/feeda/assets/90103151/26bb65e0-c392-4284-b075-eea13c9ea93a)
Add an icon pls from design > approved

2023-06-29 15:27 UTC, OlesiaTr commented
> Some conflicts, fix it pls, so that I can make merge, thanks

Resolved conflict

2023-06-29 16:21 UTC, MaksVibe approved these changes

2023-06-29 16:21 UTC, merged